import { NextResponse } from 'next/server';

const restaurants = [
  { id: 'gt1', name: 'Khinkalnia', subtitle: 'The dumpling house', description: 'Tbilisi\'s most beloved khinkali spot. 15 varieties of khinkali — from classic meat to mushroom, cheese, and even chocolate dessert khinkali.', priceRange: '₾15-30', cuisine: 'Georgian', location: 'Tbilisi, Rustaveli', image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop', rating: 4.8, reviews: 312, signature: 'Mushroom khinkali with sulguni cheese' },
  { id: 'gt2', name: 'Barbarestan', subtitle: '1910 recipes revived', description: 'Based on a 1910 Georgian cookbook by Barbare Jorjadze. Every dish is a piece of history — from roasted pomegranate lamb to adjapsandali.', priceRange: '₾50-90', cuisine: 'Georgian Fine', location: 'Tbilisi, Chardin', image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop', rating: 4.9, reviews: 167, signature: 'Roasted lamb with pomegranate & tkemali' },
  { id: 'gt3', name: 'Café Leila', subtitle: 'Bohemian courtyard', description: 'A hidden garden café in the Old Town with fairy lights, Persian rugs, and the best Adjarian khachapuri in Tbilisi. Live music on weekends.', priceRange: '₾25-50', cuisine: 'Georgian-European', location: 'Tbilisi, Old Town', image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&h=600&fit=crop', rating: 4.85, reviews: 234, signature: 'Adjarian khachapuri with extra cheese' },
  { id: 'gt4', name: 'Funicular Restaurant', subtitle: 'Dine above the city', description: 'Perched on Mtatsminda hill with a 360° view of Tbilisi. Fine Georgian dining with live piano and the best kharcho soup in town.', priceRange: '₾60-120', cuisine: 'Georgian Fine', location: 'Tbilisi, Mtatsminda', image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=600&fit=crop', rating: 4.75, reviews: 198, signature: 'Kharcho with Imeretian cheese' },
  { id: 'gt5', name: 'Porto Franco', subtitle: 'Seaside elegance', description: 'Batumi\'s finest seafood restaurant on the Bulvar. Grilled Black Sea fish, local wine, and the sound of waves. Reserve for sunset.', priceRange: '₾40-80', cuisine: 'Seafood-Georgian', location: 'Batumi, Boulevard', image: 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=800&h=600&fit=crop', rating: 4.82, reviews: 145, signature: 'Black Sea trout with pomegranate sauce' },
  { id: 'gt6', name: 'Schuchmann Wine House', subtitle: 'Vineyard dining', description: 'Dine among the vines at a family winery in Kakheti. Five-course tasting menu paired with qvevri wines. The view stretches to the Caucasus.', priceRange: '₾70-130', cuisine: 'Georgian Wine Pairing', location: 'Kakheti, Telavi', image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&h=600&fit=crop', rating: 4.95, reviews: 89, signature: 'Five-course wine pairing menu' },
  { id: 'gt7', name: 'Shavi Lomi', subtitle: 'The black lion', description: 'A cozy Tbilisi basement restaurant serving modern Georgian cuisine. Try the fried sulguni with honey and the chvishtari (cornbread with cheese).', priceRange: '₾30-60', cuisine: 'Modern Georgian', location: 'Tbilisi, Vera', image: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&h=600&fit=crop', rating: 4.88, reviews: 176, signature: 'Fried sulguni with forest honey' },
  { id: 'gt8', name: 'Retro', subtitle: 'Soviet chic', description: 'A time-capsule restaurant in Batumi with Soviet-era décor, vinyl records, and classic Georgian dishes from the 1960s. The khachapuri is legendary.', priceRange: '₾20-45', cuisine: 'Georgian Traditional', location: 'Batumi, Old Town', image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&h=600&fit=crop', rating: 4.72, reviews: 203, signature: 'Megrelian khachapuri' },
];

const dishes = [
  { name: 'Khachapuri', type: 'Bread & Cheese', desc: 'Gooey cheese-filled bread. The Adjarian version is a "cheese boat" with egg & butter on top. A UNESCO Intangible Cultural Heritage nominee.', region: 'All Georgia', image: 'https://images.unsplash.com/photo-1601050690597-df0568f7095c?w=400&h=300&fit=crop' },
  { name: 'Khinkali', type: 'Dumplings', desc: 'Juicy soup dumplings filled with spiced meat, mushrooms, or cheese. Eat them with your hands — bite the top, slurp the broth, then enjoy.', region: 'All Georgia', image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=300&fit=crop' },
  { name: 'Badrijani Nigvzit', type: 'Appetizer', desc: 'Fried eggplant rolls stuffed with walnut paste, garlic, and herbs. Topped with pomegranate seeds. The perfect start to any supra.', region: 'Tbilisi, Kakheti', image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop' },
  { name: 'Mtsvadi', type: 'Grilled Meat', desc: 'Georgian BBQ — chunks of pork or beef marinated in pomegranate juice and spices, grilled over vine wood. Served with tkemali (plum sauce).', region: 'All Georgia', image: 'https://images.unsplash.com/photo-1558030006-450675393462?w=400&h=300&fit=crop' },
  { name: 'Kharcho', type: 'Soup', desc: 'A rich beef soup with walnuts, rice, garlic, and the signature spice — blue fenugreek (utskho suneli). Hearty and deeply flavorful.', region: 'Tbilisi, Samegrelo', image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop' },
  { name: 'Churchkhela', type: 'Sweet', desc: 'Georgian "Snikers" — walnuts threaded on string, dipped in grape juice concentrate (tatara), and dried. A natural energy bar from Kakheti.', region: 'Kakheti', image: 'https://images.unsplash.com/photo-1611597617090-9a03915d5c35?w=400&h=300&fit=crop' },
  { name: 'Pkhali', type: 'Veggie', desc: 'Finely chopped spinach, beetroot, or cabbage mixed with walnut paste and spices. A rainbow of healthy, flavorful vegetarian dishes.', region: 'All Georgia', image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop' },
  { name: 'Lobiani', type: 'Bread', desc: 'Bean-filled bread, baked in a tone (clay oven). A hearty snack from the Racha region, often eaten during Lent. Simple, satisfying, delicious.', region: 'Racha', image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop' },
  { name: 'Chakapuli', type: 'Stew', desc: 'Spring lamb stew with tarragon, tkemali (green plum sauce), and white wine. A seasonal delicacy that tastes like Georgian spring.', region: 'Tbilisi, Kakheti', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop' },
  { name: 'Chvishtari', type: 'Bread', desc: 'Cornbread with sulguni cheese from Samegrelo region. Crispy outside, gooey inside. Often served with honey or as a side to stews.', region: 'Samegrelo', image: 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=400&h=300&fit=crop' },
];

export async function GET() {
  return NextResponse.json({ restaurants, dishes });
}
