import { NextResponse } from 'next/server';

const experiences = [
  { id: 'gm1', title: 'Qvevri Wine Workshop', subtitle: '8,000-year tradition in a clay pot', description: 'Visit a family vineyard in Kakheti and make wine the ancient way — buried in qvevri (clay vessels). Taste the vintage straight from the earth.', price: 120, duration: '4 hours', location: 'Kakheti, Sighnaghi', image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&h=600&fit=crop', category: 'wine', rating: 4.9, reviews: 43, included: ['Transport', 'Wine tasting (6 varieties)', 'Traditional dinner', 'English guide'] },
  { id: 'gm2', title: 'Supra Cooking Class', subtitle: 'Feast like a Georgian', description: 'Learn to make khinkali, khachapuri, and three secret family dishes with a local grandmother in her Tbilisi home. Then feast on what you made.', price: 85, duration: '3 hours', location: 'Tbilisi, Old Town', image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop', category: 'food', rating: 4.95, reviews: 78, included: ['Ingredients', 'Recipe booklet', 'Dinner with wine', 'Take-home spices'] },
  { id: 'gm3', title: 'Kazbegi Sunrise Hike', subtitle: 'Above the clouds to Gergeti', description: 'A guided sunrise hike to Gergeti Trinity Church at 2,170m. Watch the sun paint Mount Kazbek gold while sipping hot tea at the top.', price: 65, duration: '5 hours', location: 'Stepantsminda, Kazbegi', image: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&h=600&fit=crop', category: 'adventure', rating: 4.88, reviews: 56, included: ['Guide', 'Headlamps', 'Hot tea & snacks', 'Photos'] },
  { id: 'gm4', title: 'Sulfur Bath & Massage Ritual', subtitle: 'Ancient Abanotubani tradition', description: 'Experience Tbilisi\'s legendary sulfur baths in the historic Abanotubani district. Private bath with honey scrub, oak leaf massage, and chai.', price: 150, duration: '2 hours', location: 'Tbilisi, Abanotubani', image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=600&fit=crop', category: 'wellness', rating: 4.85, reviews: 92, included: ['Private bath', 'Honey scrub', 'Massage', 'Herbal tea'] },
  { id: 'gm5', title: 'Georgian Polyphonic Singing Workshop', subtitle: 'Sing with the locals', description: 'Join a master of Georgian polyphonic folk singing in a 200-year-old Tbilisi courtyard. Learn a song in 3 parts — no musical experience needed.', price: 55, duration: '2 hours', location: 'Tbilisi, Mtatsminda', image: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800&h=600&fit=crop', category: 'culture', rating: 4.92, reviews: 34, included: ['Instructor', 'Wine & snacks', 'Recording of your session'] },
  { id: 'gm6', title: 'Pottery in Kakheti', subtitle: 'Shape clay, connect to history', description: 'Work with a master potter in a traditional Kakhetian studio. Shape your own qvevri clay pot or a personal souvenir using 500-year-old techniques.', price: 70, duration: '3 hours', location: 'Kakheti, Telavi', image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&h=600&fit=crop', category: 'crafts', rating: 4.8, reviews: 27, included: ['Materials', 'Firing', 'Your creation shipped home'] },
  { id: 'gm7', title: 'Black Sea Sunset Cruise', subtitle: 'Batumi coastline at golden hour', description: 'Private sailing along the Batumi coast with views of the Old Boulevard, ferris wheel, and sunset over the Black Sea. Includes sparkling wine.', price: 200, duration: '2.5 hours', location: 'Batumi, Coastline', image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&h=600&fit=crop', category: 'adventure', rating: 4.93, reviews: 61, included: ['Private boat', 'Sparkling wine', 'Finger food', 'Photos'] },
  { id: 'gm8', title: 'Svaneti Tower Stay', subtitle: 'Sleep in a UNESCO watchtower', description: 'Spend a night in a restored 12th-century Svaneti defensive tower. Ancient stone walls, modern comfort, and breakfast with views of the Caucasus.', price: 250, duration: '1 night', location: 'Mestia, Svaneti', image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop', category: 'culture', rating: 4.97, reviews: 19, included: ['Overnight stay', 'Dinner & breakfast', 'Museum tour', 'Guide'] },
  { id: 'gm9', title: 'Khachapuri Baking Class', subtitle: 'Master the cheese boat', description: 'Learn the art of Adjarian khachapuri from a Batumi chef. Mix, stretch, fill with local cheese, and crack the egg at exactly the right moment.', price: 60, duration: '2 hours', location: 'Batumi', image: 'https://images.unsplash.com/photo-1601050690597-df0568f7095c?w=800&h=600&fit=crop', category: 'food', rating: 4.9, reviews: 88, included: ['Ingredients', 'Tasting', 'Recipe card', 'Certificate'] },
  { id: 'gm10', title: 'Paragliding Over Gudauri', subtitle: 'Soar the Caucasus', description: 'Tandem paragliding from 3,000m over the Greater Caucasus range. A 20-minute flight with views of the entire Gudauri valley and distant Kazbek.', price: 180, duration: '1.5 hours', location: 'Gudauri', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop', category: 'adventure', rating: 4.87, reviews: 45, included: ['Tandem flight', 'GoPro video', 'Insurance', 'Transfer'] },
  { id: 'gm11', title: 'Wine & Cheese Pairing at Tsinandali', subtitle: 'Estate tasting with history', description: 'Private tasting at the historic Tsinandali Estate — once home to Georgian nobility. Sample 5 wines paired with local cheeses in the palace cellar.', price: 95, duration: '2 hours', location: 'Kakheti, Telavi', image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&h=600&fit=crop', category: 'wine', rating: 4.94, reviews: 37, included: ['Estate tour', 'Wine tasting', 'Cheese board', 'English guide'] },
  { id: 'gm12', title: 'Forgotten Streets Photo Walk', subtitle: 'Capture Tbilisi\'s soul', description: 'A photography walk through Tbilisi\'s hidden courtyards, crumbling balconies, and secret staircases with a professional photographer-guide.', price: 45, duration: '3 hours', location: 'Tbilisi, Various', image: 'https://images.unsplash.com/photo-1565019011337-2faf179e0042?w=800&h=600&fit=crop', category: 'culture', rating: 4.83, reviews: 52, included: ['Photographer guide', 'Editing tips', 'Digital copies'] },
];

export async function GET() {
  return NextResponse.json(experiences);
}
